# Generated by Django 3.1.2 on 2020-11-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_score', models.IntegerField()),
                ('rel_pos', models.IntegerField()),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='stormy.userword')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stormy.userword')),
            ],
        ),
        migrations.AddField(
            model_name='userword',
            name='cloud',
            field=models.ManyToManyField(related_name='_userword_cloud_+', through='stormy.WordRelation', to='stormy.UserWord'),
        ),
        migrations.AddField(
            model_name='userword',
            name='user_storm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stormy.storm'),
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word', to='stormy.word'),
        ),
        migrations.AddField(
            model_name='storm',
            name='catalyst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stormy.userword'),
        ),
        migrations.AddField(
            model_name='storm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
