# Generated by Django 3.1.2 on 2020-10-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_score', models.IntegerField()),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial', to='stormy.userword')),
                ('next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next', to='stormy.userword')),
            ],
        ),
        migrations.AddField(
            model_name='userword',
            name='cloud',
            field=models.ManyToManyField(to='stormy.WordRelation'),
        ),
        migrations.AddField(
            model_name='userword',
            name='user_storm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stormy.storm'),
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stormy.word'),
        ),
        migrations.AddField(
            model_name='storm',
            name='catalyst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stormy.userword'),
        ),
        migrations.AddField(
            model_name='storm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile'),
        ),
    ]
